## Numpy array & Basics

In [4]:
import numpy as np

### Creating Array from list

In [5]:
arr_1d = np.array([1,2,3,4,5])
print("1d array :",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array :",arr_2d)

1d array : [1 2 3 4 5]
2d array : [[1 2 3]
 [4 5 6]]


### List vs Numpy arrays

In [7]:
py_list = [1,2,3,4,5]
print("Python list Multiplication:",py_list*2)

np_array = np.array([1,2,3,4,5]) #element wise Multiplication
print("Python array Multiplication:",np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\nList operation time:", time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print("\nNumpy operation time:", time.time() - start)

Python list Multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Python array Multiplication: [ 2  4  6  8 10]

List operation time: 0.08727121353149414

Numpy operation time: 0.0059893131256103516


### Creating array from scratch

In [ ]:
#array or matrix of zeros
zeros = np.zeros((3,4))
print("Zeros Array:\n", zeros)

#array or matrix of Ones
ones = np.ones((2,2))
print("Ones Array:\n", ones)

#array or matrix of spical const
full = np.full((3,2), 7)
print("Full Array:\n", full)

#array or matrix of random numbers
randam = np.random.random((2,3)) #the values allways in between 0 to 1
print("Random Array:\n", randam)

#array or matrix of sequence of number
sequence = np.arange(0,10) #start,stop,step(default 1)
print("Sequence Array:\n", sequence)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]]
Full Array:
 [[7 7]
 [7 7]
 [7 7]]
Random Array:
 [[0.51268319 0.92249181 0.09181842]
 [0.02342996 0.84242127 0.31723353]]
Sequence Array:
 [0 1 2 3 4 5 6 7 8 9]
