## Numpy array operations

In [2]:
import numpy as np

### Slicing

In [3]:
arr = np.arange(10)

print("Basic Slicing:", arr[2:7])
print("With step:", arr[2:7:2])
print("Negative indexing:", arr[-3])

Basic Slicing: [2 3 4 5 6]
With step: [2 4 6]
Negative indexing: 7


### Indexing And Slicing on 2d array

In [4]:
arr_2d = np.array([[1,2,3],
                   [4,5,6]])

print("Specific Element:", arr_2d[1,2]) #[row , colum]
print("Entire row:", arr_2d[1]) #print complete row
print("Entire colum:", arr_2d[:,1])

Specific Element: 6
Entire row: [4 5 6]
Entire colum: [2 5]


## Sorting

In [5]:
unshorted = np.array([6,4,5,8,3,79,5,3,3,7,9])
print("Sorted array:", np.sort(unshorted))

arr_2d_unshorted = np.array([[3,5,1],[6,1,2],[7,2,3]])
print("Sorted 2d array by colum:\n", np.sort(arr_2d_unshorted, axis = 0)) # mainly used
print("Sorted 2d array by row:\n", np.sort(arr_2d_unshorted, axis = 1))

Sorted array: [ 3  3  3  4  5  5  6  7  8  9 79]
Sorted 2d array by colum:
 [[3 1 1]
 [6 2 2]
 [7 5 3]]
Sorted 2d array by row:
 [[1 3 5]
 [1 2 6]
 [2 3 7]]


## Filter

In [6]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = num[num % 2 == 0] #it is an spical type of array because of numpy(is a mask)
print("Even Numbers:", even_num)

odd_num = num[num % 2 != 0] #it is an spical type of array because of numpy
print("Odd Numbers:", odd_num)

Even Numbers: [ 2  4  6  8 10]
Odd Numbers: [1 3 5 7 9]


### filter with mask

In [7]:
# only in numpy we use this type of syntex
mask = num > 5 #the mask will store the whole expretion in it
print("Numbers greater then 5:", num[mask])

Numbers greater then 5: [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [8]:
indices = [0,2,4]# using multi indices
print(num[indices])

where_re = np.where(num > 5)
print(where_re)# it stores the indices
print("NP where", num[where_re])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [20]:
condition_array = np.where(num > 5, num*2 , num) # search more about it!!!
# condition_array = np.where(num > 5, "true" , "false")
print(condition_array)

# For better understand we can do it like it
# if(num > 5){[     condition]
#     num*2         [true]
# }else{
#     num           [false]
# }

arr_12 = np.random.random((4,5))
print(arr_12)

ad = np.where(arr_12 > 0.5, 1,0)
print(ad)

[ 1  2  3  4  5 12 14 16 18 20]
[[0.89358978 0.45565229 0.43391311 0.80862697 0.93899434]
 [0.75189833 0.32406959 0.95983827 0.10603466 0.37583967]
 [0.53744069 0.70027859 0.91610661 0.02644797 0.88567601]
 [0.59378806 0.83905723 0.84659866 0.12576831 0.47938797]]
[[1 0 0 1 1]
 [1 0 1 0 0]
 [1 1 1 0 1]
 [1 1 1 0 0]]


### Adding and Removing Data

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

#combined = arr1 + arr2 #it will add the element of the arrrays but we want to concatenate it: Output->[5,7,9]
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### array compatibily

In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Compatibility shape:\n", a.shape == b.shape)
print("Compatibility shape:\n", a.shape == c.shape)

Compatibility shape:
 False
Compatibility shape:
 True


In [29]:
original = np.array([[1,2,3,4],
                     [4,5,6,7]])
new_row = np.array([1,2,3,4])
with_new_row = np.vstack((original, new_row))

print("Orignal:\n", original)
print("\nAfter Addind rowing:\n", with_new_row)

Orignal:
 [[1 2 3 4]
 [4 5 6 7]]

After Addind rowing:
 [[1 2 3 4]
 [4 5 6 7]
 [1 2 3 4]]
