## Numpy array operations

In [2]:
import numpy as np

### Slicing

In [ ]:
arr = np.arange(10)

print("Basic Slicing:", arr[2:7])
print("With step:", arr[2:7:2])
print("Negative indexing:", arr[-3])

Basic Slicing: [2 3 4 5 6]
With step: [2 4 6]
Negative indexing: 7


### Indexing And Slicing on 2d array

In [13]:
arr_2d = np.array([[1,2,3],
                   [4,5,6]])

print("Specific Element:", arr_2d[1,2]) #[row , colum]
print("Entire row:", arr_2d[1]) #print complete row
print("Entire colum:", arr_2d[:,1])

Specific Element: 6
Entire row: [4 5 6]
Entire colum: [2 5]


## Sorting

In [19]:
unshorted = np.array([6,4,5,8,3,79,5,3,3,7,9])
print("Sorted array:", np.sort(unshorted))

arr_2d_unshorted = np.array([[3,5,1],[6,1,2],[7,2,3]])
print("Sorted 2d array by colum:\n", np.sort(arr_2d_unshorted, axis = 0)) # mainly used
print("Sorted 2d array by row:\n", np.sort(arr_2d_unshorted, axis = 1))

Sorted array: [ 3  3  3  4  5  5  6  7  8  9 79]
Sorted 2d array by colum:
 [[3 1 1]
 [6 2 2]
 [7 5 3]]
Sorted 2d array by row:
 [[1 3 5]
 [1 2 6]
 [2 3 7]]


## Filter

In [ ]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = num[num % 2 == 0] #it is an spical type of array because of numpy(is a mask)
print("Even Numbers:", even_num)

odd_num = num[num % 2 != 0] #it is an spical type of array because of numpy
print("Odd Numbers:", odd_num)

Even Numbers: [ 2  4  6  8 10]
Odd Numbers: [1 3 5 7 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 0  2  4  6  8 10 12 14 16 18]


### filter with mask

In [28]:
# only in numpy we use this type of syntex
mask = num > 5 #the mask will store the whole expretion in it
print("Numbers greater then 5:", num[mask])

Numbers greater then 5: [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [34]:
indices = [0,2,4]# using multi indices
print(num[indices])

where_re = np.where(num > 5)
print(where_re)# it stores the indices
print("NP where", num[where_re])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(num > 5, num*2 , num) # search more about it!!!
# condition_array = np.where(num > 5, "true" , "false")
print(condition_array)

# For better understand we can do it like it
# if(num > 5){[     condition]
#     num*2         [true]
# }else{
#     num           [false]
# }

[ 1  2  3  4  5 12 14 16 18 20]


### Adding and Removing Data

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

#combined = arr1 + arr2 #it will add the element of the arrrays but we want to concatenate it: Output->[5,7,9]
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]
