## Numpy array & Basics

In [ ]:
import numpy as np

### Creating Array from list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1d array :",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array :",arr_2d)

1d array : [1 2 3 4 5]
2d array : [[1 2 3]
 [4 5 6]]


### List vs Numpy arrays

In [3]:
py_list = [1,2,3,4,5]
print("Python list Multiplication:",py_list*2)

np_array = np.array([1,2,3,4,5]) #element wise Multiplication
print("Python array Multiplication:",np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\nList operation time:", time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print("\nNumpy operation time:", time.time() - start)

Python list Multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Python array Multiplication: [ 2  4  6  8 10]

List operation time: 0.13758158683776855

Numpy operation time: 0.01796889305114746


### Creating array from scratch

In [7]:
#array or matrix of zeros
zeros = np.zeros((3,4))
print("Zeros Array:\n", zeros)

#array or matrix of Ones
ones = np.ones((2,2))
print("Ones Array:\n", ones)

#array or matrix of spical const
full = np.full((3,2), 5)
print("Full Array:\n", full)

#array or matrix of random numbers
randam = np.random.random((2,3)) #the values allways in between 0 to 1
print("Random Array:\n", randam)

#array or matrix of sequence of number
sequence = np.arange(0,10) #start,stop,step(default 1)
print("Sequence Array:\n", sequence)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]]
Full Array:
 [[5 5]
 [5 5]
 [5 5]]
Random Array:
 [[0.18020158 0.36498354 0.80961884]
 [0.50176143 0.27030514 0.98519185]]
Sequence Array:
 [0 1 2 3 4 5 6 7 8 9]


### Vector, Matrix & Tensor

In [10]:
#1d array
vector = np.array([1,2,3,4,5])
print("Vector:\n", vector)

#2d array
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix:\n", matrix)

#more then 2d are known as tensor
tensor = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[0,1,2]]])
print("Tensor:\n", tensor)

Vector:
 [1 2 3 4 5]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]


### Properties of Array

In [16]:
arr = np.array([[1,2,3],
                [4,5,6]]) #you can even store different datatypes but it is now ideal in numpy

arr1 = np.array([[1,2,3],
                [4,5,True]]) 

arr2 = np.array([[1,2,3],
                [4,5,3.14]]) 

arr3 = np.array([[1,2,3],
                [4,5,"3.14"]]) 

print("Shape of Arr", arr.shape)
print("Dimension of Arr", arr.ndim)
print("Size of Arr", arr.size)

print("\nData type of Arr", arr.dtype)
print("Data type of Arr1", arr1.dtype)
print("Data type of Arr2", arr2.dtype)
print("Data type of Arr3", arr3.dtype)

Shape of Arr (2, 3)
Dimension of Arr 2
Size of Arr 6

Data type of Arr int64
Data type of Arr1 int64
Data type of Arr2 float64
Data type of Arr3 <U21


### Array reshapeing

In [23]:
arr = np.arange(20)
print("\nOrignal Array:\n", arr)

#reshape the array means converting it into 2do or more 
#or even you can change the Dimension of matrix
reshape = arr.reshape((5,4))
print("\nReshaped Array:\n", reshape)

#to convert the martix into an array or called "flattend"
flattened = reshape.flatten()
print("\nflattened Array:\n", flattened)

# raveled(returns view, instand of copy)
raveled = reshape.ravel()
print("\nraveled Array:\n", raveled)

#Transpose
transpose = reshape.T
print("\nTranspose Array:\n", transpose)


Orignal Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

flattened Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

raveled Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Transpose Array:
 [[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
